platform :ios, '7.0'
pod 'ParseUI'
pod 'ParseFacebookUtilsV4'
pod 'FastttCamera'
pod 'ReactiveTableViewBinding'
pod 'NYXImagesKit'
pod 'ClusterPrePermissions', :path => '../ClusterPrePermissions'
pod 'AFDropdownNotification'
pod 'jot'
pod 'NSURLConnection-Blocks'
