platform :ios, '7.0'
pod 'ParseUI'
pod 'ParseFacebookUtilsV4'
pod 'FastttCamera'
pod 'ReactiveTableViewBinding'
pod 'NYXImagesKit'
pod 'ClusterPrePermissions', :git => 'https://github.com/adamjuhasz/ClusterPrePermissions.git'
pod 'AFDropdownNotification'
pod 'jot'
